### ISSUE TITLE
Research Software Reactor: GitHub actions for RSE-like tasks

### ISSUE THREAD

**Issue by trallard** [research-software-reactor/devops-for-research-sprint#1]
# Project Proposal
Develop a series of GitHub actions that could help with common tasks in a research context. These will then be published in the GH marketplace for ready use and adoption of multiple users. Some examples are:
- Installing anaconda in the CI/CD enviroment
- Sanitising Jupyter notebooks on push to the repo (i.e. apply black, clean outputs)
- Regular dependencies upgrade
- Compiling and generation of pdf outputs from Latex files
- Jupyter book related tasks

There are tons of options these are only a few

## What is the name and focus area of this project?

This would be "GitHub actions for reproducible research". The aim is to help folks to get started with CI/CD on github without too much overhead

## Who will be the project lead(s)?

@trallard 

## Who will be the team member(s)?

Open to anyone interested

| Name | GitHub Handle |
| ---- | ------------- |

## What are the initial unit(s) of work the project will target?

*  A set of GitHub actions to create
* Published release on Marketplace
* A repo to track other actions that would be useful for the community

## Skills required

* Coding in whatever preferred language you have

## Is there anything else relevant to the scope of this project?
Not right now

cc/ @research-software-reactor/core v-team

**Comment by abhidg** [comment]
We've developed a Github Action to ensure that Jupyter notebooks in a repository do not have superfluous information such as outputs and execution counts. It's available at https://github.com/marketplace/actions/ensure-clean-jupyter-notebooks. Contributors: @abhidg, @fcooper8472, @JAEarly

**Comment by JimMadge** [comment]
[Here](https://github.com/marketplace/actions/ford-documentation) is an action to build documentation for Fortran projects using [FORD](https://github.com/Fortran-FOSS-Programmers/ford).

**Comment by sohailmerchant** [comment]
We did a custom action which copy files (around 20GB) from multiple github repos and run some processing python script to collect the metadata from these files.  The output generated in json are then push to the repo back. https://github.com/sohailmerchant/test-actions.  Contributor: @jack89roberts

**Comment by ggorman** [comment]
This was a great idea. I am going to close this now but I encourage everyone to add individual issues here proposing specific actions.

**Comment by ggorman** [comment]
This was a great idea. I am going to close this now but I encourage everyone to add individual issues here proposing specific actions.
