### ISSUE TITLE
Testing FEniCS on High-Performance Computers.

### ISSUE THREAD

**Issue by js947** [research-software-reactor/devops-for-research-sprint#2]
# Project Proposal

## What is the name and focus area of this project?

**Testing FEniCS on High-Performance Computers**

Extend the testing of the [FEniCS](fenicsproject.org) project to include parallel tests that run on HPC systems. 

## Who will be the project lead(s)?

@chrisrichardson and @js947

## Who will be the team member(s)?

| Name | GitHub Handle |
| Lefteris Avramidis | @avramidis |
| ---- | ------------- |

## What are the initial unit(s) of work the project will target?

* Identify a large-scale test that would be useful to run on HPC
* Design workflow to robustly build a version of FEniCS
* Design workflow with gitlab-runner to submit tests to HPC scheduler and collect results
* Collect performance data with the aim of tracking performance over time

## Skills required

* Familiarity with FEniCS
* Familiarity with HPC systems, particularly the scheduler 

## Is there anything else relevant to the scope of this project?

cc/ @research-software-reactor/core v-team
cc/ @chrisrichardson

**Comment by avramidis** [comment]
I'll join you

**Comment by chrisrichardson** [comment]
We have used GitLab runners with SSH to run our deployment of DOLFINX (https://github.com/FEniCS/dolfinx) library on the CSD3 HPC system in Cambridge (https://www.hpc.cam.ac.uk)
Subsequently, we ran the performance test (https://github.com/FEniCS/performance-test) using the deployment, and outputting a JSON file with the results.
The timings are now available on https://fenics.github.io/performance-test/ as a nice plot using JavaScript and plotly.js

**Comment by ggorman** [comment]
Closing for now. Time to get ready for the next sprint.
