### ISSUE TITLE
Research Software Reactor: Cloud Bursting for Nektar++ CI/CD

### ISSUE THREAD

**Issue by cc-a** [research-software-reactor/devops-for-research-sprint#3]
# Project Proposal

## What is the name and focus area of this project?

This project will explore using cloud resources to supplement the on-premise CI/CD system for [Nektar++](https://www.nektar.info/). Current project resources are sufficient for day-to-day development but during intensive periods and hackathons it would be helpful to use cloud resources to increase throughput of the system and streamline work. This is challenging as Nektar++ depends on features such as build caching with ccache to provide acceptable performance.

## Who will be the project lead(s)?

@cc-a
@mdave

## Who will be the team member(s)?

| Name | GitHub Handle |
| ---- | ------------- |

## What are the initial unit(s) of work the project will target?

* Setup up cloud VM, install and configure gitlab-runner + docker
* AND/OR setup Azure Kubernetes Sevice instance
* Setup block storage for distributed cache
* Investigate/design debugging workflow for failed jobs

## Skills required

* Familiarity with GitLab CI

## Is there anything else relevant to the scope of this project?

cc/ @research-software-reactor/core v-team

**Comment by cc-a** [comment]
# What we did

Created Kubernetes cluster on azure. Use az command line to get credentials
(you can do this in cloud shell via the Azure web portal to avoid installing):

> az login ...
> az aks get-credentials --admin --resource-group <resource-group-name> --name <kubernetes-cluster-name>

This creates ~/.kube/config, this contains admin access token. Get properly
formatted CA certificate using:

> kubectl config view --raw -o json | jq -r '.clusters[0].cluster."certificate-authority-data"' | tr -d '"' | base64 --decode

This is enough information to add a Kubernetes cluster via the GitLab UI.

After creation, install Helm/Tiller and gitlab runner via GitLab UI. This
automatically creates a runner for the project.

For the .gitlab-yml you need to be using Docker-in-Docker to build Docker
images and have some global config setup:

> variables:
>   DOCKER_HOST: tcp://localhost:2375
>   DOCKER_TLS_CERTDIR: ""
> 
> services:
>   - docker:19.03.1-dind
> 
> job1:
>   tags:
>     - kubernetes
>   image:
>     docker:19.03.1

Get info on your kubernetes:
> kubectl get -n gitlab-managed-apps pods
> kubectl get -n gitlab-managed-apps pods -o wide # more info

The argument provided after -n will be "managed-apps" + any prefix specified
when setting up the cluster in GitLab.

# Cache

As Azure does not provide S3 api compatible storage we had to find a way to do
this. Created a pod in the cluster using minio to act as the cache:
> kubectl run -n gitlab-managed-apps minio --image=minio/minio --port=9000 server /data

This uses the default credentials "minioadmin" for both keys. See minio docs for
using non-default credentials. Before it's ready to use you need to create a
bucket for the cache. Need to access the pod containing minio for this. Use get
pods to find the pod name, then:

> kubectl exec -n gitlab-managed-apps -it CONTAINER_NAME bash

From this shell, just make a directory in /data to create a bucket:

> mkdir /data/cache

To configure the cache with the runner you'll need the above credentials and the
IP of the cache container. You can get the IP using `get pods` with the `-o
wide` option.

# Configure Runner

In order to configure the runner you need to get access to the pod which
contains it. Use the same process as accessing the cache container above.You can
then edit /home/gitlab-runner/.gitlab-runner/config.toml and reload the config
with:

> kill -HUP 1

This is all extremely non-ideal. If the runner container dies it will be
restarted with the default config. To make this permanent the only approach
seems to be not installing runner via the GitLab UI but modifying the Helm chart
that GitLab uses to do this -
https://docs.gitlab.com/runner/install/kubernetes.html - and the runner
manually. Have yet to try this.

## Concurrency

You want the concurrency setting of the runner to match the maximum number of
jobs that can run simultaneously on the cluster (or the max that can be
autoscaled up to). Otherwise you'll have jobs starting but unable to launch a
pod.

## CPU Limits

Use the cpu_limit to control the amount of resources available to each pod. This
will affect placement of pods on nodes.

## Polling timeout

If not using autoscaling/you expect to reach its limits then you may have
started jobs waiting for pods to launch for a while. The poll_timeout setting
changes how long the job will wait for a container to launch before failing.

## Cache use

Runner config should look something like:

>  [runners.cache]
>    Type = "s3"
>    Shared = true
>    [runners.cache.s3]
>      ServerAddress = "10.244.4.8:9000"
>      AccessKey = "minioadmin"
>      SecretKey = "minioadmin"
>      BucketName = "cache"
>      Insecure = true


Alternatively something with kubernetes volumes could probably be figured out.

# Autoscaling

Scale up is faster than scale down. This can be enabled for the resource group
in Azure. You can check if it is considering scaling up or down:

> kubectl get configmap -n kube-system cluster-autoscaler-status -o yaml

When scaling down, pods may be killed and started again on a new host this leads
to problems with persistant configuration with some of the hacky stuff done
above.

# Needed

Caching:
* pod must survive auto scaling 
* OR adapter for making S3 calls to Azure object storage...
* OR use object storage on another cloud provider
* OR have local S3/NFS storage

Runner:
* pod must survive auto scaling
* Better would changing helm configuration used by Gitlab to change default
  runner configuration

**Comment by ggorman** [comment]
Closing for now. Time to get ready for the next sprint.
