### ISSUE TITLE
Research Software Reactor: JuCorTeX Continuously-integrated Open-source Reproducible TeX for Julia code

### ISSUE THREAD

**Issue by mxochicale** [research-software-reactor/devops-for-research-sprint#4]
# Project Proposal
JuCorTeX: Continuously-integrated Open-source Reproducible TeX for Julia code

## What is the name and focus area of this project?
The aim of [corTeX](https://github.com/mxochicale/my-cortex) is to make scientific articles open source and reproducible. corTeX is for python code and it is developed by [Rodrigo Luger](https://github.com/rodluger). For this workshop, however, it is proposed a similar version of corTeX but for Julia code called "JuCorTeX: Continuously-integrated Open-source Reproducible TeX for Julia code". In a similar fashion, JuCorTeX will do two things: 
1. it will define `\oscaption` command that adds links to the exact script that generates figures, and 
2. it will define `\proof` environment which adds a link to any equation pointing a proof. 

## Who will be the project lead(s)?
@mxochicale 

## Who will be the team member(s)?

| Name | GitHub Handle |
| ---- | ------------- |

## What are the initial unit(s) of work the project will target?

* Identify which tools and workflows are more suitable for JuCorTex
* Setup Azure Pipelines or GitHub actions for LaTeX and Julia code
* Debug workflow

## Skills required

* Familiarity with CI/CD tools

## Is there anything else relevant to the scope of this project?

cc/ @research-software-reactor/core v-team

**Comment by ggorman** [comment]
Closing for now. Time to get ready for the next sprint.
